/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_stxpy_jni_Jtest */

#ifndef _Included_com_stxpy_jni_Jtest
#define _Included_com_stxpy_jni_Jtest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_stxpy_jni_Jtest
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_stxpy_jni_Jtest_sayHello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
